language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
  - "iojs"
branches:
  only:
    - gh-pages
    - /.*/
before-install:
  - pip install pep8
  - $(which npm) install -g jslint
before-script:
  - pep8 *.py
  - npm run lint
script:
  - npm test
